### ISSUE TITLE
Security issue: site cant load worker.win.js 

### ISSUE THREAD

**Issue by shruuub** [sys-256/Duino-JS#7]
Uhh yeah. Just tryed it out and it gave me that error. Any idea why?

**Comment by sys-256** [comment]
Do you mean this one ?
![](https://i.ibb.co/mXR2Fcc/image-2021-07-04-201549.png)

Or this one if you are using chrome:
![](https://i.ibb.co/sP0Z555/image-2021-07-04-201716.png)

Well, [that's because you can't run Web Workers on local files.](https://stackoverflow.com/questions/21408510/chrome-cant-load-web-worker) So if you just downloaded the repository and opened example.html, it won't work.

To make it work, you need to run a web server like Apache, NGINX or if you are using VS Code, you can use [Live Server.](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)

**Comment by shruuub** [comment]
Yeah, no it works! Thanks!
